# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/benz/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),benz)

$(call add-radio-file-sha1-checked,radio/abl.img,a5443506746103a5acc6ede588b8dabe3cc1a60f)
$(call add-radio-file-sha1-checked,radio/aop.img,7b3605a5ad496cc36595e9a22486849c6b5c72e8)
$(call add-radio-file-sha1-checked,radio/aop_config.img,a0fd05e33882e481215f5f8832d16057cb8f556e)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,f976927b0b44b4f842838425cb70fe3a921e0856)
$(call add-radio-file-sha1-checked,radio/cpucp.img,8cd8c7c2327ee92fc7653571e8d6b6a5e601cf63)
$(call add-radio-file-sha1-checked,radio/devcfg.img,e55290e3a592a7c79769a1820312b94372a1f3c5)
$(call add-radio-file-sha1-checked,radio/dsp.img,1b594ddc7882de4846708c13ed10ebea84faf93e)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,722c9c6625d602a4b1d2427457415a686616ace7)
$(call add-radio-file-sha1-checked,radio/hyp.img,2466a0e0cbecff333afbd66319bef8c80f1534de)
$(call add-radio-file-sha1-checked,radio/imagefv.img,819bcb5c5c6ba1cefaf10826fc41e9813d550311)
$(call add-radio-file-sha1-checked,radio/keymaster.img,dd39a8bc2461c1a3e3794b716f958a38a5def519)
$(call add-radio-file-sha1-checked,radio/modem.img,5d94af11e273a3ae168df28b676ac94d7a485d04)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,98dd4dd4909be893360d24abfef25bf9a3bda318)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,04c9e9be09300614e6baace38640626bd85a7c9d)
$(call add-radio-file-sha1-checked,radio/qupfw.img,49f2a2650d66fcba432f36790c994bd3905da768)
$(call add-radio-file-sha1-checked,radio/shrm.img,2c0cc29cbab45dde0b3de84c7301c7603f8b7eeb)
$(call add-radio-file-sha1-checked,radio/splash.img,84e14653a04d30f754baa9e65b54069f368382bd)
$(call add-radio-file-sha1-checked,radio/tz.img,3e344fc076599687a29910f92f7f74ebceca8306)
$(call add-radio-file-sha1-checked,radio/uefi.img,38566ac8397c751f782bd45176b6074702de06fd)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c4036466f5c5fbd01b5a0e36067ae8d0b2ed02b5)
$(call add-radio-file-sha1-checked,radio/xbl.img,036506a299a10b37f82b12b83f4f17e15a9dbab8)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,3846867fcfafaf2db716c25bc7bd4c9108f626da)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,4194e5de546fc5643cc7760968685c049926ecf6)

endif
